#dubbo:
#  startup:
#    delay: 5000
#  application:
#    name: ywj-live-gateway
#    qos-enable: false
#  registry:
#    address: nacos://192.168.79.163:8848?namespace=ywj-live-project&username=nacos&password=nacos&timeout=5000
dubbo:
  application:
    qos-enable: false
  registry:
    address: N/A  # 网关不做dubbo消费、不注册dubbo

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false   # 关闭自动根据nacos生成路由，解决脏元数据报错
      # 👇手动写路由规则
      routes:
        # api业务服务路由 ywj‑live‑api‑application
        - id: ywj-live-api
          uri: http://127.0.0.1
          predicates:
            - Path=/live/api/**

      # 全局跨域配置（保留，不要写java过滤器跨域）
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
  application:
    name: ywj-live-gateway

# 网关服务端口
server:
  port: 80