#dubbo:
#  qos:
#    enable: true
#    port: 22227
#    accept-foreign-ip: false
spring:
  application:
    name: ywj-live-im-provider
  data:
    redis:
      port: 6379
      host: 192.168.79.163
      lettuce:
        pool:
          min-idle: 10
          max-active: 50
          max-idle: 20
dubbo:
  startup:
    delay: 5000
  application:
    name: ${spring.application.name}
    # 以下3行和application同级，同缩进，不属于application子项
    qos-enable: true
    qos-port: 22227
    qos-accept-foreign-ip: false
  registry:
    address: nacos://192.168.79.163:8848?namespace=ywj-live-project&username=nacos&password=nacos&timeout=5000&group=DEFAULT_GROUP
  protocol:
    name: dubbo
    port: 9008
    dubbo:
      threadpool: fixed
      dispatcher: execution
      threads: 500
      accepts: 500
server:
  port: 8091
