<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.example</groupId>
        <artifactId>ywj-live-project</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>ywj-live-framework</artifactId>
    <packaging>pom</packaging>
    <name>Archetype - ywj-live-framework</name>
    <url>http://maven.apache.org</url>
    <modules>
        <module>ywj-live-framework-web</module>
        <module>ywj-live-framework-mq</module>
    </modules>
</project>
